module.exports = {
  caseType:'consented_hospice_care_coordination', initialState:'consent_pending',
  states:['consent_pending','assessed','plan_review','scheduled','care_active','incident_escalated','handoff_review','closed'],
  createRoles:['care_coordinator','registered_nurse'],
  evidenceKinds:['consent_receipt','guardian_authority','assessment_digest','care_plan_version','schedule_coverage','medication_reconciliation','incident_record','handoff_note','communication_receipt'],
  requiredSignals:['consentVerified','assessmentVersion','scheduleCoverage','emergencyContactVerified','medicationReviewStatus','policyVersion'],
  assessmentRoles:['registered_nurse','care_coordinator','clinical_supervisor'],
  auditRoles:['clinical_supervisor','registered_nurse'],
  connectorRoles:['care_coordinator','clinical_supervisor'],
  professionalBoundary:'The service coordinates consented care and never diagnoses, prescribes, changes medication, or replaces emergency or licensed clinical judgment.',
  connectors:[
    {name:'care_provider',purpose:'consented care-plan and visit references'},
    {name:'calendar',purpose:'schedule and handoff receipts'},
    {name:'messaging',purpose:'consented communication receipts'},
    {name:'billing',purpose:'administrative billing status only'},
    {name:'emergency_contacts',purpose:'verified escalation references'},
    {name:'health_device_feed',purpose:'consented digest-only observations'},
  ],
  transitions:[
    {from:'consent_pending',action:'record_assessment',to:'assessed',roles:['registered_nurse'],requiresEvidence:true},
    {from:'assessed',action:'submit_plan_review',to:'plan_review',roles:['registered_nurse','care_coordinator'],requiresEvidence:true},
    {from:'plan_review',action:'approve_schedule',to:'scheduled',roles:['clinical_supervisor'],requiresEvidence:true,dualControl:true},
    {from:'scheduled',action:'activate_care',to:'care_active',roles:['care_coordinator'],requiresEvidence:true},
    {from:'care_active',action:'escalate_incident',to:'incident_escalated',roles:['caregiver','registered_nurse'],requiresEvidence:true},
    {from:'incident_escalated',action:'record_handoff',to:'handoff_review',roles:['registered_nurse'],requiresEvidence:true,dualControl:true},
    {from:'handoff_review',action:'close',to:'closed',roles:['clinical_supervisor'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>({disposition:!x.consentVerified||!x.emergencyContactVerified||x.scheduleCoverage!=='covered'?'safeguarding_or_coverage_hold':x.medicationReviewStatus==='qualified_review_complete'?'clinical_plan_review_required':'medication_review_required',clinicalRecommendation:null,assessmentVersion:x.assessmentVersion}),
};
